//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Danish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Danish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateTemplates.Danish", typeof(Danish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Den returnerede tidszone {0} fra serveren stemmer ikke overens med enhedens tidszone..
        /// </summary>
        internal static string ____The_returned_time_zone__0__does_not_match_with_the_device_s_time_zone_ {
            get {
                return ResourceManager.GetString("(*) The returned time zone {0} does not match with the device\'s time zone.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Den returnerede tidszone &quot;{0}&quot; stemmer ikke overens med enhedens tidszone..
        /// </summary>
        internal static string ___The_returned_time_zone___0___does_not_match_with_the_device_s_time_zone_ {
            get {
                return ResourceManager.GetString("(*)The returned time zone \"{0}\" does not match with the device\'s time zone.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s session er udløbet..
        /// </summary>
        internal static string _0__s_session_has_expired_ {
            get {
                return ResourceManager.GetString("{0}\'s session has expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} session er udløbet..
        /// </summary>
        internal static string _0__session_has_expired_ {
            get {
                return ResourceManager.GetString("{0} session has expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et nyt møde starter snart..
        /// </summary>
        internal static string A_new_meeting_starts_shortly_ {
            get {
                return ResourceManager.GetString("A new meeting starts shortly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heldagsaftaler understøttes ikke..
        /// </summary>
        internal static string All_day_events_are_currently_not_support_ {
            get {
                return ResourceManager.GetString("All day events are currently not support.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heldagsaftaler understøttes ikke..
        /// </summary>
        internal static string All_day_events_are_not_support_ {
            get {
                return ResourceManager.GetString("All day events are not support.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle ressourcer.
        /// </summary>
        internal static string All_resources {
            get {
                return ResourceManager.GetString("All resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl under synkronisering af skabelonfilen fra serveren. Se logfiler for flere detaljer..
        /// </summary>
        internal static string An_error_encountered_in_synchronizing_the_template_file_from_the_server__Please_see_logs_for_more_details_ {
            get {
                return ResourceManager.GetString("An error encountered in synchronizing the template file from the server. Please s" +
                        "ee logs for more details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl ved afsendelse af konfigurationsdata til serveren. Se logfiler for flere detaljer..
        /// </summary>
        internal static string An_error_occurre_when_send_configurations_data_to_server__Please_see_logs_for_more_details_ {
            get {
                return ResourceManager.GetString("An error occurre when send configurations data to server. Please see logs for mor" +
                        "e details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der opstod en fejl under synkronisering af skabelonfilen fra serveren. Se logfiler for flere detaljer..
        /// </summary>
        internal static string An_error_occurred_while_sending_configuration_data_to_the_server__See_logs_for_more_details_ {
            get {
                return ResourceManager.GetString("An error occurred while sending configuration data to the server. See logs for mo" +
                        "re details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltagere.
        /// </summary>
        internal static string Attendees {
            get {
                return ResourceManager.GetString("Attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledig.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilgængelige ressourcer.
        /// </summary>
        internal static string Available_resources {
            get {
                return ResourceManager.GetString("Available resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book nyt møde.
        /// </summary>
        internal static string Book_New_Meeting {
            get {
                return ResourceManager.GetString("Book New Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ved.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuller.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke reservere reservation, da ressourcen er optaget..
        /// </summary>
        internal static string Cannot_book_meeting_as_the_resource_is_being_occupied_ {
            get {
                return ResourceManager.GetString("Cannot book meeting as the resource is being occupied.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke reservere reservation, da ressourcen er optaget..
        /// </summary>
        internal static string Cannot_book_reservation_as_the_resource_is_being_occupied_ {
            get {
                return ResourceManager.GetString("Cannot book reservation as the resource is being occupied.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke oprette forbindelse til serveren {0}..
        /// </summary>
        internal static string Cannot_connect_to_server__0__ {
            get {
                return ResourceManager.GetString("Cannot connect to server {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke oprette reservationen, ved benyttelse af Microsoft Graph..
        /// </summary>
        internal static string Cannot_create_event_when_calling_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot create event when calling Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke oprette reservation, når du bruger Microsoft Graph..
        /// </summary>
        internal static string Cannot_create_reservation_when_using_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot create reservation when using Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke slette reservationen, ved benyttelse af Microsoft Graph..
        /// </summary>
        internal static string Cannot_delete_event_when_calling_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot delete event when calling Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke slette reservation, når du bruger Microsoft Graph..
        /// </summary>
        internal static string Cannot_delete_reservation_when_using_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot delete reservation when using Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke afslutte/forlænge reservationen, før den starter..
        /// </summary>
        internal static string Cannot_End_Extend_meeting_before_it_starts_ {
            get {
                return ResourceManager.GetString("Cannot End/Extend meeting before it starts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke afslutte/forlænge reservationen, før den starter..
        /// </summary>
        internal static string Cannot_End_Extend_reservation_before_it_starts_ {
            get {
                return ResourceManager.GetString("Cannot End/Extend reservation before it starts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke afslutte/forlænge reservationen, før den starter..
        /// </summary>
        internal static string Cannot_End_Extend_reservtion_before_it_starts_ {
            get {
                return ResourceManager.GetString("Cannot End/Extend reservtion before it starts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservationen kan ikke afsluttes, før den starter..
        /// </summary>
        internal static string Cannot_end_meeting_before_it_starts_ {
            get {
                return ResourceManager.GetString("Cannot end meeting before it starts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservationen kan ikke afsluttes, før den starter..
        /// </summary>
        internal static string Cannot_end_reservation_before_it_starts_ {
            get {
                return ResourceManager.GetString("Cannot end reservation before it starts.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke forlænge mødet. Næste møde starter om kort tid..
        /// </summary>
        internal static string Cannot_extend_meeting__The_next_meeting_starts_shortly_ {
            get {
                return ResourceManager.GetString("Cannot extend meeting. The next meeting starts shortly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke udvide møde ud over starttidspunktet for det næste møde..
        /// </summary>
        internal static string Cannot_extend_meeting_beyond_start_time_of_the_next_meeting_ {
            get {
                return ResourceManager.GetString("Cannot extend meeting beyond start time of the next meeting.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke behandle den ønskede reservation..
        /// </summary>
        internal static string Cannot_have_the_required_appointment_processed_ {
            get {
                return ResourceManager.GetString("Cannot have the required appointment processed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke behandle reservationen..
        /// </summary>
        internal static string Cannot_process_the_reservation_ {
            get {
                return ResourceManager.GetString("Cannot process the reservation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke opdatere reservationen, ved benyttelse af Microsoft Graph..
        /// </summary>
        internal static string Cannot_update_event_when_calling_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot update event when calling Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke opdatere reservation, når du bruger Microsoft Graph..
        /// </summary>
        internal static string Cannot_update_reservation_when_using_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot update reservation when using Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID-kortet er udløbet..
        /// </summary>
        internal static string Card_expired_ {
            get {
                return ResourceManager.GetString("Card expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kort ID eller brugernavn/kodeord ikke gyldigt..
        /// </summary>
        internal static string Card_ID_or_username___password_not_valid_ {
            get {
                return ResourceManager.GetString("Card ID or username / password not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft succesfuldt..
        /// </summary>
        internal static string Confirm_Success_ {
            get {
                return ResourceManager.GetString("Confirm Success.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunikationsproblemer eller server {0} understøtter ikke denne funktion..
        /// </summary>
        internal static string Connection_error_or_server__0__does_not_support_this_feature_ {
            get {
                return ResourceManager.GetString("Connection error or server {0} does not support this feature.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opret konto.
        /// </summary>
        internal static string Create_Account {
            get {
                return ResourceManager.GetString("Create Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problembeskrivelsen blev gemt.
        /// </summary>
        internal static string Create_report_problem_is_successfully {
            get {
                return ResourceManager.GetString("Create report problem is successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne reservation er ikke blevet synkroniseret endnu. Prøv venligst igen senere..
        /// </summary>
        internal static string Current_appointment_has_not_yet_been_confirmed_by_the_server__please_try_again_in_few_minutes_ {
            get {
                return ResourceManager.GetString("Current appointment has not yet been confirmed by the server, please try again in" +
                        " few minutes.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuværende møde arrangeret af.
        /// </summary>
        internal static string Current_event_organized_by {
            get {
                return ResourceManager.GetString("Current event organized by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødeleder.
        /// </summary>
        internal static string Current_meeting_organized_by {
            get {
                return ResourceManager.GetString("Current meeting organized by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Emne.
        /// </summary>
        internal static string Default_Subject {
            get {
                return ResourceManager.GetString("Default Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enten emailadresse eller kontonavn er forkert..
        /// </summary>
        internal static string Either_email_address_or_account_name_is_wrong_ {
            get {
                return ResourceManager.GetString("Either email address or account name is wrong.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enten er Emne, Email, Starttidspunkt eller Sluttidspunkt ikke udfyldt..
        /// </summary>
        internal static string Either_Subject__Resource_email__Starttime_or_Endtime_is_null_ {
            get {
                return ResourceManager.GetString("Either Subject, Resource email, Starttime or Endtime is null.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enten emailadresse eller kontonavn er forkert..
        /// </summary>
        internal static string Email_address_or_account_name_is_wrong_ {
            get {
                return ResourceManager.GetString("Email address or account name is wrong.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slut.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slut nuværende møde?.
        /// </summary>
        internal static string End_current_meeting_ {
            get {
                return ResourceManager.GetString("End current meeting?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutdatoen er tidligere end startdatoen..
        /// </summary>
        internal static string End_date_is_earlier_than_Start_date_ {
            get {
                return ResourceManager.GetString("End date is earlier than Start date.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFSLUT / FORLÆNG.
        /// </summary>
        internal static string END_OR_EXTEND {
            get {
                return ResourceManager.GetString("END OR EXTEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluttid.
        /// </summary>
        internal static string End_Time {
            get {
                return ResourceManager.GetString("End Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluttid:.
        /// </summary>
        internal static string End_Time_ {
            get {
                return ResourceManager.GetString("End Time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluttidspunktet er tidligere end starttidspunktet..
        /// </summary>
        internal static string End_time_is_earlier_than_start_time_ {
            get {
                return ResourceManager.GetString("End time is earlier than start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast email-adresse.
        /// </summary>
        internal static string Enter_email_address {
            get {
                return ResourceManager.GetString("Enter email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast adgangskode.
        /// </summary>
        internal static string Enter_Password {
            get {
                return ResourceManager.GetString("Enter Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast dine oplysninger.
        /// </summary>
        internal static string Enter_Your_Information {
            get {
                return ResourceManager.GetString("Enter Your Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv dit kodeord.
        /// </summary>
        internal static string Enter_your_password {
            get {
                return ResourceManager.GetString("Enter your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast din PIN kode.
        /// </summary>
        internal static string Enter_your_PIN_code {
            get {
                return ResourceManager.GetString("Enter your PIN code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv dit brugernavn.
        /// </summary>
        internal static string Enter_your_username {
            get {
                return ResourceManager.GetString("Enter your username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved oprettelse af problem beskrivelse.
        /// </summary>
        internal static string Error_creating_problem_description {
            get {
                return ResourceManager.GetString("Error creating problem description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl i konfigurationsfilen..
        /// </summary>
        internal static string Error_in_configuration_file_ {
            get {
                return ResourceManager.GetString("Error in configuration file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl i konfigurationsfil {0}..
        /// </summary>
        internal static string Error_in_configuration_file__0__ {
            get {
                return ResourceManager.GetString("Error in configuration file {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved oprettelse af aftale. Kontroller forbindelsen til server.
        /// </summary>
        internal static string Error_in_creating_appointment__Please_check_the_connection_to_DSS_for_Server {
            get {
                return ResourceManager.GetString("Error in creating appointment. Please check the connection to DSS for Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved oprettelse af reservationen. Kontroller forbindelsen til DSS for Server..
        /// </summary>
        internal static string Error_in_creating_appointment__Please_check_the_connection_to_DSS_for_Server_ {
            get {
                return ResourceManager.GetString("Error in creating appointment. Please check the connection to DSS for Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved afslutning af reservationen. Kontroller venligst, om [Settings; Server tidzone] er korrekt valgt..
        /// </summary>
        internal static string Error_in_ending_appointment__Please_check_if__Settings__Server_time_zone__is_correctly_selected_ {
            get {
                return ResourceManager.GetString("Error in ending appointment. Please check if [Settings; Server time zone] is corr" +
                        "ectly selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved afslutning af reservationen. Kontroller forbindelsen til DSS for Server..
        /// </summary>
        internal static string Error_in_ending_appointment__Please_check_the_connection_to_DSS_for_Server_ {
            get {
                return ResourceManager.GetString("Error in ending appointment. Please check the connection to DSS for Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved forlængelse af reservationen. Kontroller venligst, om [Settings; Server tidzone] er korrekt valgt..
        /// </summary>
        internal static string Error_in_extending_appointment__Please_check_if__Settings__Server_time_zone__is_correctly_selected_ {
            get {
                return ResourceManager.GetString("Error in extending appointment. Please check if [Settings; Server time zone] is c" +
                        "orrectly selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved forlængelse af reservationen. Kontroller forbindelsen til DSS for Server..
        /// </summary>
        internal static string Error_in_extending_appointment__Please_check_the_connection_to_DSS_for_Server_ {
            get {
                return ResourceManager.GetString("Error in extending appointment. Please check the connection to DSS for Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl i skabelonfilen..
        /// </summary>
        internal static string Error_in_the_template_file_ {
            get {
                return ResourceManager.GetString("Error in the template file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl i skabelonfilen {0}..
        /// </summary>
        internal static string Error_in_the_template_file__0__ {
            get {
                return ResourceManager.GetString("Error in the template file {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl ved oprettelse af problem beskrivelse.
        /// </summary>
        internal static string Error_when_create_report_problem {
            get {
                return ResourceManager.GetString("Error when create report problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Møder.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forlæng.
        /// </summary>
        internal static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORLÆNG RESERVATIONEN.
        /// </summary>
        internal static string EXTEND_BOOKING {
            get {
                return ResourceManager.GetString("EXTEND BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forlæng møde.
        /// </summary>
        internal static string Extend_Meeting {
            get {
                return ResourceManager.GetString("Extend Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forlæng reservation.
        /// </summary>
        internal static string Extend_Reservation {
            get {
                return ResourceManager.GetString("Extend Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forlængelsestiden skal være længere end sluttidspunkt..
        /// </summary>
        internal static string Extend_time_must_be_greater_than_end_time_ {
            get {
                return ResourceManager.GetString("Extend time must be greater than end time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opsætningen af sammenhængen mellem brugeren og kortet mislykkedes. Prøv venligst igen senere eller kontakt din administrator..
        /// </summary>
        internal static string Failed_to_set_up_the_association_between_the_user_and_the_card__Please_try_again_later_or_contact_your_administrator_ {
            get {
                return ResourceManager.GetString("Failed to set up the association between the user and the card. Please try again " +
                        "later or contact your administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokationsoversigt.
        /// </summary>
        internal static string Floor_Map {
            get {
                return ResourceManager.GetString("Floor Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID-kortet er udløbet..
        /// </summary>
        internal static string ID_card_has_expired_ {
            get {
                return ResourceManager.GetString("ID card has expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig konto, (PIN-kode og kort-id blev ikke fundet), opret en ny konto eller kontakt din administrator.
        /// </summary>
        internal static string Invalid_account___PIN_Code_og_Card_id_not_found___please_create_a_new_Account_or_contact_you_administrator {
            get {
                return ResourceManager.GetString("Invalid account, (PIN Code og Card id not found), please create a new Account or " +
                        "contact you administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig konto, (PIN-kode og kort-id blev ikke fundet), opret en ny konto eller kontakt din administrator.
        /// </summary>
        internal static string Invalid_account___PIN_Code_or_Card_id_not_found___please_create_a_new_Account_or_contact_your_administrator {
            get {
                return ResourceManager.GetString("Invalid account, (PIN Code or Card id not found), please create a new Account or " +
                        "contact your administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldigt kort..
        /// </summary>
        internal static string Invalid_card_ {
            get {
                return ResourceManager.GetString("Invalid card.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig information.
        /// </summary>
        internal static string Invalid_information {
            get {
                return ResourceManager.GetString("Invalid information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forkert kodeord.
        /// </summary>
        internal static string Invalid_password {
            get {
                return ResourceManager.GetString("Invalid password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tastatur.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listevisning.
        /// </summary>
        internal static string List_View {
            get {
                return ResourceManager.GetString("List View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opret møde.
        /// </summary>
        internal static string Make_meeting {
            get {
                return ResourceManager.GetString("Make meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opret møde.
        /// </summary>
        internal static string Make_reservation {
            get {
                return ResourceManager.GetString("Make reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Møde.
        /// </summary>
        internal static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødelokale er ledigt.
        /// </summary>
        internal static string Meeting_room_is_available {
            get {
                return ResourceManager.GetString("Meeting room is available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødelokale er ledigt.
        /// </summary>
        internal static string Meeting_room_is_available_now {
            get {
                return ResourceManager.GetString("Meeting room is available now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Møder.
        /// </summary>
        internal static string Meetings {
            get {
                return ResourceManager.GetString("Meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværket er ikke tilgængeligt.
        /// </summary>
        internal static string Network_is_unreachable {
            get {
                return ResourceManager.GetString("Network is unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netværket er ikke tilgængeligt..
        /// </summary>
        internal static string Network_is_unreachable_ {
            get {
                return ResourceManager.GetString("Network is unreachable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NY RESERVATION.
        /// </summary>
        internal static string NEW_BOOKING {
            get {
                return ResourceManager.GetString("NEW BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NY RESERVATION.
        /// </summary>
        internal static string NEW_RESERVATION {
            get {
                return ResourceManager.GetString("NEW RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NÆSTE RESERVATION STARTER SNART.
        /// </summary>
        internal static string NEXT_BOOKING_STARTS_SHORTLY {
            get {
                return ResourceManager.GetString("NEXT BOOKING STARTS SHORTLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næste møde kl. {0}.
        /// </summary>
        internal static string Next_meeting_at__0_ {
            get {
                return ResourceManager.GetString("Next meeting at {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næste møde starter om kort tid.
        /// </summary>
        internal static string Next_meeting_starts_shortly {
            get {
                return ResourceManager.GetString("Next meeting starts shortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næste møder og events.
        /// </summary>
        internal static string Next_meetings_and_events {
            get {
                return ResourceManager.GetString("Next meetings and events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næste reservation kl. {0}.
        /// </summary>
        internal static string Next_reservation_at__0_ {
            get {
                return ResourceManager.GetString("Next reservation at {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næste reservation starter om kort tid.
        /// </summary>
        internal static string Next_reservation_starts_shortly {
            get {
                return ResourceManager.GetString("Next reservation starts shortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Næste reservationer og events.
        /// </summary>
        internal static string Next_reservations_and_events {
            get {
                return ResourceManager.GetString("Next reservations and events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke flere reservationer i dag.
        /// </summary>
        internal static string No_further_meetings_today {
            get {
                return ResourceManager.GetString("No further meetings today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke flere reservationer i dag[NEWLINE][NEWLINE]Lav en ny reservation ved at  klikke på.
        /// </summary>
        internal static string No_further_meetings_today_NEWLINE__NEWLINE_Book_a_new_reservation_by_tapping_the_screen {
            get {
                return ResourceManager.GetString("No further meetings today[NEWLINE][NEWLINE]Book a new reservation by tapping the " +
                        "screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen møder i dag.
        /// </summary>
        internal static string No_meetings_today {
            get {
                return ResourceManager.GetString("No meetings today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen netværksforbindelse.
        /// </summary>
        internal static string No_Network_connection {
            get {
                return ResourceManager.GetString("No Network connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen reservationer i dag.
        /// </summary>
        internal static string No_reservations_today {
            get {
                return ResourceManager.GetString("No reservations today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optaget.
        /// </summary>
        internal static string Occupied {
            get {
                return ResourceManager.GetString("Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTAGET INDTIL {0} - {1}.
        /// </summary>
        internal static string OCCUPIED__0_____1_ {
            get {
                return ResourceManager.GetString("OCCUPIED {0} - {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugte ressourcer.
        /// </summary>
        internal static string Occupied_resources {
            get {
                return ResourceManager.GetString("Occupied resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation mislykkedes.
        /// </summary>
        internal static string Operation_failed {
            get {
                return ResourceManager.GetString("Operation failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiseret af.
        /// </summary>
        internal static string Organized_by {
            get {
                return ResourceManager.GetString("Organized by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangør.
        /// </summary>
        internal static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangør:.
        /// </summary>
        internal static string Organizer_ {
            get {
                return ResourceManager.GetString("Organizer:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangørens e-mail:.
        /// </summary>
        internal static string Organizer_Email_ {
            get {
                return ResourceManager.GetString("Organizer Email:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangørens navn:.
        /// </summary>
        internal static string Organizer_Name_ {
            get {
                return ResourceManager.GetString("Organizer Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adgangskode.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adgangskode er påkrævet..
        /// </summary>
        internal static string Password_is_required_ {
            get {
                return ResourceManager.GetString("Password is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN kode.
        /// </summary>
        internal static string Personal_ID {
            get {
                return ResourceManager.GetString("Personal ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN kode eksisterede allerede, vælg en anden kode..
        /// </summary>
        internal static string Personal_ID_already_existed_ {
            get {
                return ResourceManager.GetString("Personal ID already existed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN kode er påkrævet..
        /// </summary>
        internal static string Personal_ID_is_required_ {
            get {
                return ResourceManager.GetString("Personal ID is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN kode.
        /// </summary>
        internal static string PIN_code {
            get {
                return ResourceManager.GetString("PIN code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN kode eksisterede allerede, vælg en anden kode..
        /// </summary>
        internal static string PIN_code_already_existed__choose_another_code_ {
            get {
                return ResourceManager.GetString("PIN code already existed, choose another code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN kode er påkrævet..
        /// </summary>
        internal static string PIN_code_is_required_ {
            get {
                return ResourceManager.GetString("PIN code is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN koder er ikke ens..
        /// </summary>
        internal static string PIN_codes_are_not_the_same_ {
            get {
                return ResourceManager.GetString("PIN codes are not the same.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjek venligst din indbakke for en valideringsmail, hvor du kan aktivere din konto..
        /// </summary>
        internal static string Please_check_your_inbox_for_a_validation_mail_where_you_can_activate_your_account_ {
            get {
                return ResourceManager.GetString("Please check your inbox for a validation mail where you can activate your account" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft venligst reservationen. Hvis ikke bekræftet, afsluttes den efter {0} minut (er) efter starttidspunktet..
        /// </summary>
        internal static string Please_confirm_the_booking__If_not_confirmed__the_booking_will_be_ended_after__0__minute_s__after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the booking. If not confirmed, the booking will be ended after {0}" +
                        " minute(s) after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft møde. [NEWLINE] Hvis der ikke bekræftes, afsluttes mødet {0} minuter efter starttidspunkt..
        /// </summary>
        internal static string Please_confirm_the_meeting___NEWLINE_If_not_confirmed__the_meeting_will_be_ended_after__0__minutes_after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the meeting. [NEWLINE]If not confirmed, the meeting will be ended " +
                        "after {0} minutes after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft møde. Hvis der ikke bekræftes, afsluttes mødet {0} minuter efter starttidspunkt..
        /// </summary>
        internal static string Please_confirm_the_meeting__If_not_confirmed__the_meeting_will_be_ended_after__0__minute_s__after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the meeting. If not confirmed, the meeting will be ended after {0}" +
                        " minute(s) after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft venligst mødet. Hvis ikke bekræftet, afsluttes mødet efter {0} minutter efter starttidspunktet..
        /// </summary>
        internal static string Please_confirm_the_meeting__If_not_confirmed__the_meeting_will_be_ended_after__0__minutes_after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the meeting. If not confirmed, the meeting will be ended after {0}" +
                        " minutes after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft venligst reservation. Hvis der ikke bekræftes, afsluttes reservation {0} minuter efter starttidspunktet..
        /// </summary>
        internal static string Please_confirm_the_meeting__If_not_confirmed__the_reservation_will_be_ended_after__0__minutes_after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the meeting. If not confirmed, the reservation will be ended after" +
                        " {0} minutes after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft møde.[NEWLINE] Hvis der ikke bekræftes, afsluttes mødet {0} minuter efter starttidspunkt.[NEWLINE].
        /// </summary>
        internal static string Please_confirm_the_meeting__NEWLINE_If_not_confirmed__the_meeting_will_be_ended_after__0__minutes_after_start_time__NEWLINE_ {
            get {
                return ResourceManager.GetString("Please confirm the meeting.[NEWLINE]If not confirmed, the meeting will be ended a" +
                        "fter {0} minutes after start time.[NEWLINE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft venligst reservationen. Hvis ikke bekræftet, afsluttes den efter {0} minut (er) efter starttidspunktet..
        /// </summary>
        internal static string Please_confirm_the_reservation__If_not_confirmed__it_will_be_ended_after__0__minute_s__after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the reservation. If not confirmed, it will be ended after {0} minu" +
                        "te(s) after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekræft venligst reservation. Hvis der ikke bekræftes, afsluttes reservation {0} minuter efter starttidspunktet..
        /// </summary>
        internal static string Please_confirm_the_reservation__If_not_confirmed__the_reservation_will_be_ended_after__0__minute_s__after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the reservation. If not confirmed, the reservation will be ended a" +
                        "fter {0} minute(s) after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast venligst en kommentar.
        /// </summary>
        internal static string Please_input_a_comment {
            get {
                return ResourceManager.GetString("Please input a comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryk på skærmen for at reservere mødelokale.
        /// </summary>
        internal static string Please_tap_the_screen_to_book_instant_meeting {
            get {
                return ResourceManager.GetString("Please tap the screen to book instant meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryk på skærmen for at reservere mødelokale.
        /// </summary>
        internal static string Please_tap_the_screen_to_book_new_meeting {
            get {
                return ResourceManager.GetString("Please tap the screen to book new meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryk på skærmen for at reservere mødelokale.
        /// </summary>
        internal static string Please_tap_the_screen_to_book_new_reservation {
            get {
                return ResourceManager.GetString("Please tap the screen to book new reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryk på skærmen for at afslutte eller forlænge nuværende møde.
        /// </summary>
        internal static string Please_tap_the_screen_to_end_extend_current_meeting {
            get {
                return ResourceManager.GetString("Please tap the screen to end/extend current meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryk på skærmen for at afslutte eller forlænge nuværende møde.
        /// </summary>
        internal static string Please_tap_the_screen_to_end_extend_the_meeting {
            get {
                return ResourceManager.GetString("Please tap the screen to end/extend the meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryk på skærmen for at afslutte eller forlænge nuværende møde.
        /// </summary>
        internal static string Please_tap_the_screen_to_end_extend_the_reservation {
            get {
                return ResourceManager.GetString("Please tap the screen to end/extend the reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN koder er ikke ens..
        /// </summary>
        internal static string Re_enter_personal_ID_is_incorrect_ {
            get {
                return ResourceManager.GetString("Re-enter personal ID is incorrect.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genstart.
        /// </summary>
        internal static string Remote_Restart {
            get {
                return ResourceManager.GetString("Remote Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapporter et problem.
        /// </summary>
        internal static string Report_a_problem {
            get {
                return ResourceManager.GetString("Report a problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapporter problem.
        /// </summary>
        internal static string Report_problem {
            get {
                return ResourceManager.GetString("Report problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        internal static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservationen findes allerede..
        /// </summary>
        internal static string Reservation_on_same_timeslot_already_exists_ {
            get {
                return ResourceManager.GetString("Reservation on same timeslot already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource.
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource findes ikke..
        /// </summary>
        internal static string Resource_does_not_exist_ {
            get {
                return ResourceManager.GetString("Resource does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource-e-mail:.
        /// </summary>
        internal static string Resource_Email_ {
            get {
                return ResourceManager.GetString("Resource Email:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource email {0} findes ikke i Exchange Server..
        /// </summary>
        internal static string Resource_email__0__does_not_exist_in_Exchange_Server_ {
            get {
                return ResourceManager.GetString("Resource email {0} does not exist in Exchange Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource navn:.
        /// </summary>
        internal static string Resource_Name_ {
            get {
                return ResourceManager.GetString("Resource Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource- eller mødearrangør findes ikke..
        /// </summary>
        internal static string Resource_or_Meeting_organizer_does_not_exist_ {
            get {
                return ResourceManager.GetString("Resource or Meeting organizer does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource eller mødearrangør eksisterer ikke..
        /// </summary>
        internal static string Resource_or_organizer_does_not_exist_ {
            get {
                return ResourceManager.GetString("Resource or organizer does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fra.
        /// </summary>
        internal static string Resource_Status_From {
            get {
                return ResourceManager.GetString("Resource Status From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødelokale.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversigt i dag.
        /// </summary>
        internal static string Room_schedule_today {
            get {
                return ResourceManager.GetString("Room schedule today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vælg dato.
        /// </summary>
        internal static string Select_Date {
            get {
                return ResourceManager.GetString("Select Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsendelse af heartbeat til server {0} mislykkedes..
        /// </summary>
        internal static string Sending_heartbeat_to_server__0__failed_ {
            get {
                return ResourceManager.GetString("Sending heartbeat to server {0} failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server anmodning udløbet..
        /// </summary>
        internal static string Server_request_timed_out_ {
            get {
                return ResourceManager.GetString("Server request timed out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis alle mødelokaler.
        /// </summary>
        internal static string Show_all_meeting_rooms {
            get {
                return ResourceManager.GetString("Show all meeting rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis alle mødelokaler.
        /// </summary>
        internal static string Show_all_rooms {
            get {
                return ResourceManager.GetString("Show all rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis kun ubrugte mødelokaler.
        /// </summary>
        internal static string Show_only_unused_meeting_rooms {
            get {
                return ResourceManager.GetString("Show only unused meeting rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis kun brugte mødelokaler.
        /// </summary>
        internal static string Show_only_used_meeting_rooms {
            get {
                return ResourceManager.GetString("Show only used meeting rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noget gik galt i komunikationen med serveren. Kontroller venligst forbindelsen..
        /// </summary>
        internal static string Something_went_wrong_in_communication_with_the_Server__Please_check_connection_ {
            get {
                return ResourceManager.GetString("Something went wrong in communication with the Server. Please check connection.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunikation til serveren ikke muligt. Kontroller forbindelsen til den..
        /// </summary>
        internal static string Something_went_wrong_in_DSS_for_Server__Please_check_the_connection_to_it_ {
            get {
                return ResourceManager.GetString("Something went wrong in DSS for Server. Please check the connection to it.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starttidspunkt.
        /// </summary>
        internal static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emne.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emne:.
        /// </summary>
        internal static string Subject_ {
            get {
                return ResourceManager.GetString("Subject:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfuldt..
        /// </summary>
        internal static string Success_ {
            get {
                return ResourceManager.GetString("Success.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aflæs dit kort.
        /// </summary>
        internal static string Swipe_your_card {
            get {
                return ResourceManager.GetString("Swipe your card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryk på skærmen for at reservere mødelokalet.
        /// </summary>
        internal static string Tab_screen_to_reserve_the_meeting_room {
            get {
                return ResourceManager.GetString("Tab screen to reserve the meeting room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRYK PÅ SKÆRMEN  FOR AT RESERVER.
        /// </summary>
        internal static string TAP_TO_BOOK {
            get {
                return ResourceManager.GetString("TAP TO BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRYK PÅ SKÆRMEN FOR AT ÆNDRE.
        /// </summary>
        internal static string TAP_TO_END_EXTEND_BOOKING {
            get {
                return ResourceManager.GetString("TAP TO END/EXTEND BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationen af Modern Authentication har fejl, kontakt Administrator..
        /// </summary>
        internal static string The_config_of_Modern_Authentication_has_error_ {
            get {
                return ResourceManager.GetString("The config of Modern Authentication has error.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationen og skabelonen er blevet opdateret.
        /// </summary>
        internal static string The_configuration___template_has_been_refreshed {
            get {
                return ResourceManager.GetString("The configuration & template has been refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationen af Modern Authentication har fejl, kontakt Administrator..
        /// </summary>
        internal static string The_configuration_of_Modern_Authentication_has_errors__contact_the_Administrator_ {
            get {
                return ResourceManager.GetString("The configuration of Modern Authentication has errors, contact the Administrator." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutdatoen er tidligere end startdatoen..
        /// </summary>
        internal static string The_end_date_you_entered_occurs_before_the_start_date_ {
            get {
                return ResourceManager.GetString("The end date you entered occurs before the start date.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forlængelsestiden skal være længere end sluttidspunkt..
        /// </summary>
        internal static string The_extension_time_must_be_longer_than_the_end_time_ {
            get {
                return ResourceManager.GetString("The extension time must be longer than the end time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opsætningen af sammenhængen mellem brugeren og kortet mislykkedes. Prøv venligst igen senere eller kontakt din administrator..
        /// </summary>
        internal static string The_link_between_the_user_and_card_was_unsuccessful__please_try_again_later_or_contact_your_administrator_ {
            get {
                return ResourceManager.GetString("The link between the user and card was unsuccessful, please try again later or co" +
                        "ntact your administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødelokale er ledigt.
        /// </summary>
        internal static string The_meeting_room_is_available {
            get {
                return ResourceManager.GetString("The meeting room is available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødet begynder om kort tid..
        /// </summary>
        internal static string The_meeting_will_start_shortly_ {
            get {
                return ResourceManager.GetString("The meeting will start shortly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} har ikke den tilsvarende udvekslingsserver..
        /// </summary>
        internal static string The_resource__0__does_not_have_its_corresponding_exchange_server_ {
            get {
                return ResourceManager.GetString("The resource {0} does not have its corresponding exchange server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressourcen er usynlig..
        /// </summary>
        internal static string The_resource_is_invisible_ {
            get {
                return ResourceManager.GetString("The resource is invisible.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressourcen med e-mail {0} eksisterer ikke..
        /// </summary>
        internal static string The_resource_with_email__0__does_not_exist_ {
            get {
                return ResourceManager.GetString("The resource with email {0} does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den valgte ressource er ikke tilgængelig..
        /// </summary>
        internal static string The_selected_resource_is_not_available_ {
            get {
                return ResourceManager.GetString("The selected resource is not available.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skabelonen kan ikke indlæses, efter den er hente fra den lokale maskine..
        /// </summary>
        internal static string The_template_cannot_be_loaded_after_it_is_downloaded_from_the_local_machine_ {
            get {
                return ResourceManager.GetString("The template cannot be loaded after it is downloaded from the local machine.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skabelonen kan ikke indlæses, efter den er hente fra den lokale maskine..
        /// </summary>
        internal static string The_template_cannot_be_reloaded_when_it_is_retrieved_from_local_machine_ {
            get {
                return ResourceManager.GetString("The template cannot be reloaded when it is retrieved from local machine.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er en fejl komunikationen til servers API fra {0}..
        /// </summary>
        internal static string There_is_an_error_s__when_getting_server_information_api_from__0__ {
            get {
                return ResourceManager.GetString("There is an error(s) when getting server information api from {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er en eller flere fejl, når der hentes serveroplysninger api fra {0}..
        /// </summary>
        internal static string There_is_an_error_s__when_getting_server_information_api_from__0___ {
            get {
                return ResourceManager.GetString("There is an error(s) when getting server information api from {0} .", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette ID-kort er blevet deaktiveret af administratoren..
        /// </summary>
        internal static string This_account_has_been_disabled_by_the_Administrator_ {
            get {
                return ResourceManager.GetString("This account has been disabled by the Administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette id-kort er blevet deaktiveret af administratoren..
        /// </summary>
        internal static string This_Card_has_been_disabled_by_the_Administrator_ {
            get {
                return ResourceManager.GetString("This Card has been disabled by the Administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette kort er gyldigt fra {0} til {1}..
        /// </summary>
        internal static string This_card_is_valid_from__0__to__1__ {
            get {
                return ResourceManager.GetString("This card is valid from {0} to {1}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne enhed har ikke godkendt konfigurationsfilen..
        /// </summary>
        internal static string This_device_has_not_approved_the_configuration_file_ {
            get {
                return ResourceManager.GetString("This device has not approved the configuration file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne enhed venter på godkendelse fra denne server..
        /// </summary>
        internal static string This_device_is_waiting_for_approval_from_this_server_ {
            get {
                return ResourceManager.GetString("This device is waiting for approval from this server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette digitale skilt blev ikke registreret korrekt på serversiden\nLuk appen og foretag konfigurationen igen.
        /// </summary>
        internal static string This_digital_sign_was_not_registered_correctly_on_the_server_side_nPlease_close_app_and_do_the_configuration_again {
            get {
                return ResourceManager.GetString("This digital sign was not registered correctly on the server side\\nPlease close a" +
                        "pp and do the configuration again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne funktion er blevet deaktiveret af administratoren..
        /// </summary>
        internal static string This_function_has_been_disabled_by_the_Administrator_ {
            get {
                return ResourceManager.GetString("This function has been disabled by the Administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne funktion understøttes kun af en nyere server version..
        /// </summary>
        internal static string This_function_only_supports_by_a_newer_server_version_ {
            get {
                return ResourceManager.GetString("This function only supports by a newer server version.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne funktion understøttes kun af en nyere server version..
        /// </summary>
        internal static string This_function_only_supports_new_server_ {
            get {
                return ResourceManager.GetString("This function only supports new server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mødet begynder om kort tid..
        /// </summary>
        internal static string This_meeting_starts_shortly_ {
            get {
                return ResourceManager.GetString("This meeting starts shortly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne reservation er ikke blevet synkroniseret endnu. Prøv venligst igen senere..
        /// </summary>
        internal static string This_reservation_has_not_been_syncronized_yet__Please_try_again_later_ {
            get {
                return ResourceManager.GetString("This reservation has not been syncronized yet. Please try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to til {0}.
        /// </summary>
        internal static string to__0_ {
            get {
                return ResourceManager.GetString("to {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagens møder og events.
        /// </summary>
        internal static string Today_meetings_and_events {
            get {
                return ResourceManager.GetString("Today meetings and events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagens reservationer.
        /// </summary>
        internal static string Today_s_reservations {
            get {
                return ResourceManager.GetString("Today\'s reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugte ressourcer.
        /// </summary>
        internal static string Used_resources {
            get {
                return ResourceManager.GetString("Used resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugernavn.
        /// </summary>
        internal static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugernavn er påkrævet..
        /// </summary>
        internal static string User_name_is_required_ {
            get {
                return ResourceManager.GetString("User name is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDIGT INDTIL {0}.
        /// </summary>
        internal static string VACANT_UNTIL__0_ {
            get {
                return ResourceManager.GetString("VACANT UNTIL {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meget snart vil et nyt digitalt skilt være klar til brug\nVent venligst mens dit nye digitale skilt bliver tilmeldt.
        /// </summary>
        internal static string Very_soon_a_new_digital_sign_will_be_ready_for_use_nPlease_wait_while_your_new_digital_sign_is_being_enrolled {
            get {
                return ResourceManager.GetString("Very soon a new digital sign will be ready for use\\nPlease wait while your new di" +
                        "gital sign is being enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velkommen {0}. Din session slutter 30 sekunder efter dit sidste tryk på skærmen..
        /// </summary>
        internal static string Welcome__0___Your_session_will_end_30_seconds_after_your_last_touch_on_the_screen_ {
            get {
                return ResourceManager.GetString("Welcome {0}. Your session will end 30 seconds after your last touch on the screen" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan reservere mødelokalet ved at trykke på skærmen.
        /// </summary>
        internal static string You_can_book_a_new_meeting_by_tapping_this_screen {
            get {
                return ResourceManager.GetString("You can book a new meeting by tapping this screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan kun afslutte / udvide et møde, hvis du er mødearrangør..
        /// </summary>
        internal static string You_can_only_end_extend_a_meeting_if_you_are_the_meeting_organizer_ {
            get {
                return ResourceManager.GetString("You can only end/extend a meeting if you are the meeting organizer.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan kun afslutte/forlænge et møde, hvis du er mødearrangør..
        /// </summary>
        internal static string You_can_only_end_extend_a_meeting_if_you_are_the_organizer_ {
            get {
                return ResourceManager.GetString("You can only end/extend a meeting if you are the organizer.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan ikke booke denne ressource, fordi ressourcen er lukket. Åbningstider fra {0} til {1}..
        /// </summary>
        internal static string You_cannot_book_this_resource_because_the_resource_is_closed__Opening_hours_from__0__to__1__ {
            get {
                return ResourceManager.GetString("You cannot book this resource because the resource is closed. Opening hours from " +
                        "{0} to {1}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan ikke booke denne ressource, fordi ressourcen er lukket. Åbningstider fra {0} til {1}..
        /// </summary>
        internal static string You_cannot_book_this_resource_because_the_resource_out_of_open_hours__Opening_hours_from__0__to__1__ {
            get {
                return ResourceManager.GetString("You cannot book this resource because the resource out of open hours. Opening hou" +
                        "rs from {0} to {1}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du skal aflæse dit kort for at benytte skærmen..
        /// </summary>
        internal static string You_need_to_swipe_your_card_to_interact_with_the_screen_ {
            get {
                return ResourceManager.GetString("You need to swipe your card to interact with the screen.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har slået Kiosk-tilstanden fra, applikationen skal genstarte for at vise navigationslinjen. Klik på &quot;&quot;OK&quot;&quot; for at fortsætte..
        /// </summary>
        internal static string You_ve_turned_off_the_Kiosk_Mode__the_application_must_restart_to_display_Navigation_Bar__Click___OK___to_continue_ {
            get {
                return ResourceManager.GetString("You\'ve turned off the Kiosk Mode, the application must restart to display Navigat" +
                        "ion Bar. Click \"\"OK\"\" to continue.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har slået kiosktilstand fra, og applikationen genstarter automatisk for at vise navigationslinjen..
        /// </summary>
        internal static string You_ve_turned_off_the_Kiosk_Mode__the_application_will_automatically_restart_to_display_Navigation_Bar_ {
            get {
                return ResourceManager.GetString("You\'ve turned off the Kiosk Mode, the application will automatically restart to d" +
                        "isplay Navigation Bar.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har slået Kiosk-tilstand til, applikationen skal genstarte for at skjule navigationslinjen. Klik på &quot;&quot;OK&quot;&quot; for at fortsætte..
        /// </summary>
        internal static string You_ve_turned_on_the_Kiosk_Mode__the_application_must_restart_to_hide_Navigation_Bar__Click___OK___to_continue_ {
            get {
                return ResourceManager.GetString("You\'ve turned on the Kiosk Mode, the application must restart to hide Navigation " +
                        "Bar. Click \"\"OK\"\" to continue.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har slået kiosktilstanden til, applikationen genstarter automatisk for at skjule navigationslinjen..
        /// </summary>
        internal static string You_ve_turned_on_the_Kiosk_Mode__the_application_will_automatically_restart_to_hide_Navigation_Bar_ {
            get {
                return ResourceManager.GetString("You\'ve turned on the Kiosk Mode, the application will automatically restart to hi" +
                        "de Navigation Bar.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din konto er ikke blevet aktiveret..
        /// </summary>
        internal static string Your_account_has_not_been_activated_ {
            get {
                return ResourceManager.GetString("Your account has not been activated.", resourceCulture);
            }
        }
    }
}
