//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Polish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Polish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateTemplates.Polish", typeof(Polish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwracana strefa czasowa nie pasuje to strefy czasowej urządzenia.
        /// </summary>
        internal static string ___The_returned_time_zone___0___does_not_match_with_the_device_s_time_zone_ {
            get {
                return ResourceManager.GetString("(*)The returned time zone \"{0}\" does not match with the device\'s time zone.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesja wygasła.
        /// </summary>
        internal static string _0__session_has_expired_ {
            get {
                return ResourceManager.GetString("{0} session has expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe spotkanie rozpocznie się wkrótce..
        /// </summary>
        internal static string A_new_meeting_starts_shortly_ {
            get {
                return ResourceManager.GetString("A new meeting starts shortly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotanie już istnieje.
        /// </summary>
        internal static string Appointment_already_existed_ {
            get {
                return ResourceManager.GetString("Appointment already existed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uczestnicy.
        /// </summary>
        internal static string Attendees {
            get {
                return ResourceManager.GetString("Attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarezerwuj nowe spotkanie..
        /// </summary>
        internal static string Book_New_Meeting {
            get {
                return ResourceManager.GetString("Book New Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można połączyć się z serwerem.
        /// </summary>
        internal static string Cannot_connect_to_server__0__ {
            get {
                return ResourceManager.GetString("Cannot connect to server {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można stworzyć rezerwacji podczas korzystania z Microsoft Graph.
        /// </summary>
        internal static string Cannot_create_reservation_when_using_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot create reservation when using Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć rezerwacji podczas korzystania z Microsoft Graph.
        /// </summary>
        internal static string Cannot_delete_reservation_when_using_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot delete reservation when using Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz przedłużyć spotkania. Następne spotkanie rozpocznie się wkrótce..
        /// </summary>
        internal static string Cannot_extend_meeting__The_next_meeting_starts_shortly_ {
            get {
                return ResourceManager.GetString("Cannot extend meeting. The next meeting starts shortly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można przedłużyć spotkania poza czas początkowy następnego spotkania..
        /// </summary>
        internal static string Cannot_extend_meeting_beyond_start_time_of_the_next_meeting_ {
            get {
                return ResourceManager.GetString("Cannot extend meeting beyond start time of the next meeting.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można przetworzyć rezerwacji.
        /// </summary>
        internal static string Cannot_process_the_reservation_ {
            get {
                return ResourceManager.GetString("Cannot process the reservation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zatualizować rezerwacji podczas korzystania z Microsoft Graph.
        /// </summary>
        internal static string Cannot_update_reservation_when_using_Microsoft_Graph_ {
            get {
                return ResourceManager.GetString("Cannot update reservation when using Microsoft Graph.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karta identyfikacyjna albo nazwa użytkownika/ hasło są nieważne.
        /// </summary>
        internal static string Card_ID_or_username___password_not_valid_ {
            get {
                return ResourceManager.GetString("Card ID or username / password not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaakceptuj.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd połączenia lub serwer {0} nie obsługuje tej funkcji..
        /// </summary>
        internal static string Connection_error_or_server__0__does_not_support_this_feature_ {
            get {
                return ResourceManager.GetString("Connection error or server {0} does not support this feature.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temat, adres email zasobu, czas początkowy lub czas końcowy są zerowe.
        /// </summary>
        internal static string Either_Subject__Resource_email__Starttime_or_Endtime_is_null_ {
            get {
                return ResourceManager.GetString("Either Subject, Resource email, Starttime or Endtime is null.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec/ Zakończ.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończyć obecne spotkanie?.
        /// </summary>
        internal static string End_current_meeting_ {
            get {
                return ResourceManager.GetString("End current meeting?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data końcowa jest wcześniej niż data początkowa.
        /// </summary>
        internal static string End_date__is_earlier_than_Start_date_ {
            get {
                return ResourceManager.GetString("End date  is earlier than Start date.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas końcowy.
        /// </summary>
        internal static string End_Time {
            get {
                return ResourceManager.GetString("End Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas końcowy jest wcześniej niż czas początkowy.
        /// </summary>
        internal static string Endtime_is_earlier_than_starttime_ {
            get {
                return ResourceManager.GetString("Endtime is earlier than starttime.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprwadź swoje dane..
        /// </summary>
        internal static string Enter_Your_Information {
            get {
                return ResourceManager.GetString("Enter Your Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź swoje hasło.
        /// </summary>
        internal static string Enter_your_password {
            get {
                return ResourceManager.GetString("Enter your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź swoją nazwę użytkownika.
        /// </summary>
        internal static string Enter_your_username {
            get {
                return ResourceManager.GetString("Enter your username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w pliku konfiguracyjnym.
        /// </summary>
        internal static string Error_in_configuration_file_ {
            get {
                return ResourceManager.GetString("Error in configuration file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w pliku konfiguracyjnym {0}.
        /// </summary>
        internal static string Error_in_configuration_file__0__ {
            get {
                return ResourceManager.GetString("Error in configuration file {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas tworzenia  spotkania. Proszę sprawdź połączenie z serwerem DSS.
        /// </summary>
        internal static string Error_in_creating_appointment__Please_check_the_connection_to_DSS_for_Server_ {
            get {
                return ResourceManager.GetString("Error in creating appointment. Please check the connection to DSS for Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas zakończenia spotkania. Proszę sprawdź czy (Ustawienia; Strefa czasowa serwera) jest prawidłowo wybrana.
        /// </summary>
        internal static string Error_in_ending_appointment__Please_check_if__Settings__Server_time_zone__is_correctly_selected_ {
            get {
                return ResourceManager.GetString("Error in ending appointment. Please check if [Settings; Server time zone] is corr" +
                        "ectly selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas zakończenia spotkania. Proszę sprawdź połączenie z serwerem DSS.
        /// </summary>
        internal static string Error_in_ending_appointment__Please_check_the_connection_to_DSS_for_Server_ {
            get {
                return ResourceManager.GetString("Error in ending appointment. Please check the connection to DSS for Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas przedłużenia spotkania. Proszę sprawdź czy (Ustawienia; Strefa czasowa serwera) jest prawidłowo wybrana.
        /// </summary>
        internal static string Error_in_extending_appointment__Please_check_if__Settings__Server_time_zone__is_correctly_selected_ {
            get {
                return ResourceManager.GetString("Error in extending appointment. Please check if [Settings; Server time zone] is c" +
                        "orrectly selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas przedłużenia spotkania. Proszę sprawdź połączenie z serwerem DSS.
        /// </summary>
        internal static string Error_in_extending_appointment__Please_check_the_connection_to_DSS_for_Server_ {
            get {
                return ResourceManager.GetString("Error in extending appointment. Please check the connection to DSS for Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w szablonie dokumentu.
        /// </summary>
        internal static string Error_in_the_template_file_ {
            get {
                return ResourceManager.GetString("Error in the template file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w szablonie dokumentu {0}.
        /// </summary>
        internal static string Error_in_the_template_file__0__ {
            get {
                return ResourceManager.GetString("Error in the template file {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedłuż.
        /// </summary>
        internal static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedłużć spotkanie.
        /// </summary>
        internal static string Extend_Meeting {
            get {
                return ResourceManager.GetString("Extend Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karta identyfikacyjna wygasła.
        /// </summary>
        internal static string ID_card_has_expired_ {
            get {
                return ResourceManager.GetString("ID card has expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotkanie.
        /// </summary>
        internal static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sieć jest nieosiągalna.
        /// </summary>
        internal static string Network_is_unreachable_ {
            get {
                return ResourceManager.GetString("Network is unreachable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następne spotkanie rozpocznie się wkrótce..
        /// </summary>
        internal static string Next_meeting_starts_shortly {
            get {
                return ResourceManager.GetString("Next meeting starts shortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następne spotkania i wydarzenia.
        /// </summary>
        internal static string Next_meetings_and_events {
            get {
                return ResourceManager.GetString("Next meetings and events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzisiaj nie ma żadnych spotkań.
        /// </summary>
        internal static string No_meetings_today {
            get {
                return ResourceManager.GetString("No meetings today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia internetowego.
        /// </summary>
        internal static string No_Network_connection {
            get {
                return ResourceManager.GetString("No Network connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja nie powiodła się.
        /// </summary>
        internal static string Operation_failed {
            get {
                return ResourceManager.GetString("Operation failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorganizowany przez.
        /// </summary>
        internal static string Organized_by {
            get {
                return ResourceManager.GetString("Organized by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizator.
        /// </summary>
        internal static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest wymagane.
        /// </summary>
        internal static string Password_is_required_ {
            get {
                return ResourceManager.GetString("Password is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę zaakceptuj swoje spotkanie. Jeśli Twoje spotkanie nie zostanie zaakceptowane, to zostanie ono zakończone w ciągu {0} minut od rozpoczęcia..
        /// </summary>
        internal static string Please_confirm_the_meeting__If_not_confirmed__the_meeting_will_be_ended_after__0__minutes_after_start_time_ {
            get {
                return ResourceManager.GetString("Please confirm the meeting. If not confirmed, the meeting will be ended after {0}" +
                        " minutes after start time.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wprowadź komentarz.
        /// </summary>
        internal static string Please_input_a_comment {
            get {
                return ResourceManager.GetString("Please input a comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę klinknij na ekran aby zakończyć/ przedłużyc obecne spotkanie..
        /// </summary>
        internal static string Please_tap_the_screen_to_end_extend_current_meeting {
            get {
                return ResourceManager.GetString("Please tap the screen to end/extend current meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoś problem.
        /// </summary>
        internal static string Report_problem {
            get {
                return ResourceManager.GetString("Report problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób nie istnieje.
        /// </summary>
        internal static string Resource_does_not_exist_ {
            get {
                return ResourceManager.GetString("Resource does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres email zasobu nie istnieje w serwerze wymiany.
        /// </summary>
        internal static string Resource_email__0__does_not_exist_in_Exchange_Server_ {
            get {
                return ResourceManager.GetString("Resource email {0} does not exist in Exchange Server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób albo Organizator nie istnieje.
        /// </summary>
        internal static string Resource_or_Meeting_organizer_does_not_exist_ {
            get {
                return ResourceManager.GetString("Resource or Meeting organizer does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykaz sal na dziś.
        /// </summary>
        internal static string Room_schedule_today {
            get {
                return ResourceManager.GetString("Room schedule today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysyłanie taktowania do serwera nie powiodło się.
        /// </summary>
        internal static string Sending_heartbeat_to_server__0__failed_ {
            get {
                return ResourceManager.GetString("Sending heartbeat to server {0} failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żądanie serwera wygasło.
        /// </summary>
        internal static string Server_request_timed_out_ {
            get {
                return ResourceManager.GetString("Server request timed out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak w komunikacji z serwerem. Proszę sprawdź połączenie.
        /// </summary>
        internal static string Something_went_wrong_in_communication_with_the_Server__Please_check_connection_ {
            get {
                return ResourceManager.GetString("Something went wrong in communication with the Server. Please check connection.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj spotkania.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala konferencyjna jest dostępna..
        /// </summary>
        internal static string The_meeting_room_is_available {
            get {
                return ResourceManager.GetString("The meeting room is available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób {0} nie posiada odpowiedniego serwera wymiany.
        /// </summary>
        internal static string The_resource__0__does_not_have_its_corresponding_exchange_server_ {
            get {
                return ResourceManager.GetString("The resource {0} does not have its corresponding exchange server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób z adresem email nie istnieje.
        /// </summary>
        internal static string The_resource_with_email__0__does_not_exist_ {
            get {
                return ResourceManager.GetString("The resource with email {0} does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrany zasób jest nieosiągalny.
        /// </summary>
        internal static string The_selected_resource_is_not_available_ {
            get {
                return ResourceManager.GetString("The selected resource is not available.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojawił/y się błąd/błędy podczas pobierania informacji api z serwera.
        /// </summary>
        internal static string There_is_an_error_s__when_getting_server_information_api_from__0___ {
            get {
                return ResourceManager.GetString("There is an error(s) when getting server information api from {0} .", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta karta jest ważna od do.
        /// </summary>
        internal static string This_card_is_valid_from__0__to__1__ {
            get {
                return ResourceManager.GetString("This card is valid from {0} to {1}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta funkcja została wyłączona przez Administratora.
        /// </summary>
        internal static string This_function_has_been_disabled_by_the_Administrator_ {
            get {
                return ResourceManager.GetString("This function has been disabled by the Administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta karta identyfikacyjna została unieważniona przez Administratora.
        /// </summary>
        internal static string This_ID_Card_has_been_disabled_by_the_Administrator_ {
            get {
                return ResourceManager.GetString("This ID Card has been disabled by the Administrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika jest wymagana.
        /// </summary>
        internal static string User_name_is_required_ {
            get {
                return ResourceManager.GetString("User name is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj! Twoja sesja wygaśnie po 30 sekundach od ostatniego dotknięcia ekranu.
        /// </summary>
        internal static string Welcome__0___Your_session_will_end_30_seconds_after_your_last_touch_on_the_screen_ {
            get {
                return ResourceManager.GetString("Welcome {0}. Your session will end 30 seconds after your last touch on the screen" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możesz zorganizować nowe spotkanie poprzez kliknięcie na ten ekran..
        /// </summary>
        internal static string You_can_book_a_new_meeting_by_tapping_this_screen {
            get {
                return ResourceManager.GetString("You can book a new meeting by tapping this screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możesz zakończyć/ przedłużyć spotkanie, tylko jeśli jesteś jego organizatorem.
        /// </summary>
        internal static string You_can_only_end_extend_a_meeting_if_you_are_the_meeting_organizer_ {
            get {
                return ResourceManager.GetString("You can only end/extend a meeting if you are the meeting organizer.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz przeciągnąć swoją kartę, aby korzystać z ekranu.
        /// </summary>
        internal static string You_need_to_swipe_your_card_to_interact_with_the_screen_ {
            get {
                return ResourceManager.GetString("You need to swipe your card to interact with the screen.", resourceCulture);
            }
        }
    }
}
